// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa61lE0MevhKHiZin65fHs0-_HptFgZmA',
    appId: '1:880176719664:web:8fbe5edb7129408cf60af5',
    messagingSenderId: '880176719664',
    projectId: 'personal-diary-2026-beta',
    authDomain: 'personal-diary-2026-beta.firebaseapp.com',
    storageBucket: 'personal-diary-2026-beta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0TLyjPt1soibwuhHuIN5pdnLQC458Ds',
    appId: '1:880176719664:android:f7d6712c0c5f846bf60af5',
    messagingSenderId: '880176719664',
    projectId: 'personal-diary-2026-beta',
    storageBucket: 'personal-diary-2026-beta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSN-JsOiEh70qJpA1LADyrEGT8vxSHS3Y',
    appId: '1:880176719664:ios:ac9a3ea92f1b3e1cf60af5',
    messagingSenderId: '880176719664',
    projectId: 'personal-diary-2026-beta',
    storageBucket: 'personal-diary-2026-beta.firebasestorage.app',
    iosBundleId: 'com.example.personalDiaryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSN-JsOiEh70qJpA1LADyrEGT8vxSHS3Y',
    appId: '1:880176719664:ios:f0b86a2d3af11ec3f60af5',
    messagingSenderId: '880176719664',
    projectId: 'personal-diary-2026-beta',
    storageBucket: 'personal-diary-2026-beta.firebasestorage.app',
    iosBundleId: 'com.example.personalDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa61lE0MevhKHiZin65fHs0-_HptFgZmA',
    appId: '1:880176719664:web:65ac9b4540fc7e30f60af5',
    messagingSenderId: '880176719664',
    projectId: 'personal-diary-2026-beta',
    authDomain: 'personal-diary-2026-beta.firebaseapp.com',
    storageBucket: 'personal-diary-2026-beta.firebasestorage.app',
  );

}