name: Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --dart-define=LIVEKIT_URL=${{ secrets.LIVEKIT_URL }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_DIARY_2026_BETA }}'
          channelId: live
          projectId: personal-diary-2026-beta